### ISSUE TITLE
How to load snapshot files when upgrading from 2.17 to 2.22

### ISSUE THREAD

**Issue by dengchangshi** [memgraph/documentation#1082]
Hello, how can I use the snapshot file of version 2.17 in memgraph version 2.22?

**Comment by antejavor** [comment]
Hi @dengchangshi, this depends on several factors, but the general advice is captured here: https://memgraph.com/docs/database-management/backup-and-restore 


We didn't change the snapshot file between the mentioned versions, so that should be ok. 

Are you running a native or docker version of Memgraph?   Have you tried anything so far? Are you trying to upgrade your production instance?

**Comment by dengchangshi** [comment]
Hi @antejavor  I am using the docker version,
