### ISSUE TITLE
Add step by step instructions how to connect Prometheus to Memgraph

### ISSUE THREAD

**Issue by vpavicic** [memgraph/documentation#956]
Knowledge from this blog post needs to be incorporated into the docs page about the HTTP endpoint ->
https://memgraph.com/docs/database-management/monitoring#configure-the-http-endpoint

BLOG POST: https://memgraph.com/blog/use-prometheus-monitoring-memgraph-performance-metrics

**Comment by katarinasupe** [comment]
@antejavor you were the last one trying this out. What do you think about Vlasta's suggestion?

**Comment by katarinasupe** [comment]
all we have now https://memgraph.com/docs/database-management/monitoring#prometheus-exporter

**Comment by antejavor** [comment]
Yeah, I think this also can be closed. I added that [particular example during the improvement](https://github.com/memgraph/documentation/pull/959) of the monitoring of BP. I would close this for now since we have a basic example, and more improvements will come to Prometheus, and it will be polished with time.
